info:
  user: "DarkTyr"
  system: "SUMO1"
  wafer_type: "13AX"
  chip_ids:
    - "w00_c00_r00"
    - "w00_c00_r01"
    - "w00_c00_r02"
    - "w00_c00_r03"
    - "w00_c01_r00"
    - "w00_c02_r04"
    - "w00_c05_r06"
    - "w00_c22_r00"

test_globals:
  # Which columns to run these tests on?
  columns: [0,1,2,3,4,5,6,7]  # Supported columns 0 thru 7 or a sub set
  # System configurations parameter, may be needed when we send LSync value
  n_rows: 4  # Can't change without effecting DASTARD/Server

# Sweep SSA bias while sweeping feedback with triangle
phase0_0:
  bias_sweep_type: linear # linear / binary_search / triangle
  bias_sweep_start: 0
  bias_sweep_end: 30000
  bias_sweep_npoints: 256
  n_avg: 4  # number of averages beyond n_rows (Which get averaged across per column)
  bias_change_wait_ms: 100
  crate:
  # You may want to change the triangle paraemeters based on resistor values
    tri_steps: 12
    tri_step: 1
    tri_dwell: 0
    lsync: 256
    tri_output: FB  # We want the triangle on the FB
    data_mode: FBA_ERR

# Sweep feedback with triangle and bias to Ic_max
phase0_1:
  bias_change_wait_ms: 200
  n_avg: 4
  crate:
  # You may want to change the triangle paraemeters based on resistor values
    tri_steps: 12
    tri_step: 1
    tri_dwell: 0
    lsync: 256
    tri_output: FB  # We want the triangle on the FB
    data_mode: FBA_ERR # not sure if we should infer this or not. Honestly it will depend on what the system config has, maybe inferring is better


# Sweep the inputs with a triangle and record data
phase1_0:
  bias_change_wait_ms: 200
  n_avg: 4
  crate:
  # You may want to change the triangle paraemeters based on resistor values
    tri_steps: 9
    tri_step: 1
    tri_dwell: 0
    lsync: 256
    tri_output: IN  # We want the triangle on the FB
    data_mode: FBB_ERR # not sure if we should infer this or not. Honestly it will depend on what the system config has, maybe inferring is better

       
